services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: mssql
    command: /bin/bash /entrypoint.sh
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=.acisa159753
    volumes:
      - dbdata:/var/opt/mssql/data
      - ./db/mssql/docker-entrypoint.sh:/entrypoint.sh
      - ./db/mssql/docker-db-init.sh:/db-init.sh
      - ./db/mssql/mssql-ham.sql:/db-init.sql
    expose:
      - "1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P ".acisa159753" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  aci.ham.api:
    image: ${DOCKER_REGISTRY-}acihamapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - Serilog:WriteTo:0:Args:path=/app/log.txt
    depends_on:
      mssql:
        condition: service_healthy
    expose:
      - "5000"

volumes:
  dbdata:
