version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: mssql
    command: /bin/bash /entrypoint.sh
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=.acisa159753
    volumes:
      - dbdata:/var/opt/mssql/data
      - ./db/mssql/docker-entrypoint.sh:/entrypoint.sh
      - ./db/mssql/docker-db-init.sh:/db-init.sh
      - ./db/mssql/mssql-base.sql:/db-init.sql
    expose:
      - "1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-P.acisa159753", "-Q", "select 1"]
      interval: 1s
      retries: 60

  aci.base.api:
    image: ${DOCKER_REGISTRY-}acibaseapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - Serilog:WriteTo:0:Args:path=/app/log.txt
    depends_on:
      mssql:
        condition: service_healthy
    expose:
      - "5000"

volumes:
  dbdata:
