//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI.HAM.Mail.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAnnotations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotations() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACI.HAM.Mail.Localization.DataAnnotations", typeof(DataAnnotations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  API Key expiration notice.
        /// </summary>
        public static string _API_Key_expiration_notice {
            get {
                return ResourceManager.GetString(" API Key expiration notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occured. The mail could not be sent.
        /// </summary>
        public static string An_error_occured__The_mail_could_not_be_sent {
            get {
                return ResourceManager.GetString("An error occured. The mail could not be sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email addresses must be between {0} and {1} characters.
        /// </summary>
        public static string Email_addresses_must_be_between_and_characters {
            get {
                return ResourceManager.GetString("Email addresses must be between and characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email should have at least 3 characters.
        /// </summary>
        public static string Email_should_have_at_least_3_characters {
            get {
                return ResourceManager.GetString("Email should have at least 3 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email should have maximum 256 characters.
        /// </summary>
        public static string Email_should_have_maximum_256_characters {
            get {
                return ResourceManager.GetString("Email should have maximum 256 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiration is required.
        /// </summary>
        public static string Expiration_is_required {
            get {
                return ResourceManager.GetString("Expiration is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you didn&apos;t change your password, please contact our support team. Your security is very important to us!.
        /// </summary>
        public static string If_you_didn_t_change_your_password__please_contact_our_support_team__Your_security_is_very_important_to_us_ {
            get {
                return ResourceManager.GetString("If you didn\'t change your password, please contact our support team. Your securit" +
                        "y is very important to us!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail has successfully been sent.
        /// </summary>
        public static string Mail_has_successfully_been_sent {
            get {
                return ResourceManager.GetString("Mail has successfully been sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject is required.
        /// </summary>
        public static string Subject_is_required {
            get {
                return ResourceManager.GetString("Subject is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token is required.
        /// </summary>
        public static string Token_is_required {
            get {
                return ResourceManager.GetString("Token is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Url is required.
        /// </summary>
        public static string Url_is_required {
            get {
                return ResourceManager.GetString("Url is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must provide at least one email address.
        /// </summary>
        public static string You_must_provide_at_least_one_email_address {
            get {
                return ResourceManager.GetString("You must provide at least one email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Septeo password was just changed..
        /// </summary>
        public static string Your_Septeo_password_was_just_changed_ {
            get {
                return ResourceManager.GetString("Your Septeo password was just changed.", resourceCulture);
            }
        }
    }
}
