//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI.Proxy.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class V1_Controllers_UsersController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal V1_Controllers_UsersController() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACI.Proxy.Api.Resources.V1.Controllers.UsersController", typeof(V1_Controllers_UsersController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating the board in the database..
        /// </summary>
        internal static string Error_updating_the_board_in_the_database {
            get {
                return ResourceManager.GetString("Error updating the board in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating the building in the database..
        /// </summary>
        internal static string Error_updating_the_building_in_the_database {
            get {
                return ResourceManager.GetString("Error updating the building in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating the company in the database..
        /// </summary>
        internal static string Error_updating_the_company_in_the_database {
            get {
                return ResourceManager.GetString("Error updating the company in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating the project in the database..
        /// </summary>
        internal static string Error_updating_the_project_in_the_database {
            get {
                return ResourceManager.GetString("Error updating the project in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating the role in the database..
        /// </summary>
        internal static string Error_updating_the_role_in_the_database {
            get {
                return ResourceManager.GetString("Error updating the role in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating the room type in the database.
        /// </summary>
        internal static string Error_updating_the_room_type_in_the_database {
            get {
                return ResourceManager.GetString("Error updating the room type in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating the user in the database..
        /// </summary>
        internal static string Error_updating_the_user_in_the_database {
            get {
                return ResourceManager.GetString("Error updating the user in the database", resourceCulture);
            }
        }
    }
}
