//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI.Proxy.Mail.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Services_MailService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Services_MailService() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACI.Proxy.Mail.Resources.Services.MailService", typeof(Services_MailService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate account.
        /// </summary>
        internal static string Activate_account {
            get {
                return ResourceManager.GetString("Activate account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Button not working? Try pasting this URL into your browser:.
        /// </summary>
        internal static string Button_not_working__Try_pasting_this_URL_into_your_browser_ {
            get {
                return ResourceManager.GetString("Button not working? Try pasting this URL into your browser:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copyright.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello!.
        /// </summary>
        internal static string Hello_ {
            get {
                return ResourceManager.GetString("Hello!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you are not trying to log in, please change your password and consider changing your email to ensure the security of your account..
        /// </summary>
        internal static string If_you_are_not_trying_to_log_in__please_change_your_password_and_consider_changing_your_email_to_ensure_the_security_of_your_account_ {
            get {
                return ResourceManager.GetString("If you are not trying to log in, please change your password and consider changin" +
                        "g your email to ensure the security of your account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you didn&apos;t change your password, please contact our support team. Your security is very important to us!.
        /// </summary>
        internal static string If_you_didn_t_change_your_password__please_contact_our_support_team__Your_security_is_very_important_to_us_ {
            get {
                return ResourceManager.GetString("If you didn\'t change your password, please contact our support team. Your securit" +
                        "y is very important to us!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kind regards,.
        /// </summary>
        internal static string Kind_regards_ {
            get {
                return ResourceManager.GetString("Kind regards,", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset password.
        /// </summary>
        internal static string Reset_password {
            get {
                return ResourceManager.GetString("Reset password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template not found.
        /// </summary>
        internal static string Template_not_found {
            get {
                return ResourceManager.GetString("Template not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Septeo team..
        /// </summary>
        internal static string The_Septeo_team_ {
            get {
                return ResourceManager.GetString("The Septeo team.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This confirmation link will expire in 3 days. If you did not request an account, no further action is required..
        /// </summary>
        internal static string This_confirmation_link_will_expire_in_3_days__If_you_did_not_request_an_account__no_further_action_is_required_ {
            get {
                return ResourceManager.GetString("This confirmation link will expire in 3 days. If you did not request an account, " +
                        "no further action is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is the code you need to log into your account:.
        /// </summary>
        internal static string This_is_the_code_you_need_to_log_into_your_account_ {
            get {
                return ResourceManager.GetString("This is the code you need to log into your account:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This password reset link will expire in 60 minutes..
        /// </summary>
        internal static string This_password_reset_link_will_expire_in_60_minutes_ {
            get {
                return ResourceManager.GetString("This password reset link will expire in 60 minutes.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This password reset link will expire in 60 minutes. If you did not request a password reset, no further action is required..
        /// </summary>
        internal static string This_password_reset_link_will_expire_in_60_minutes__If_you_did_not_request_a_password_reset__no_further_action_is_required_ {
            get {
                return ResourceManager.GetString("This password reset link will expire in 60 minutes. If you did not request a pass" +
                        "word reset, no further action is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To activate your account, please click on the button below to verify your email address. Once activated, you&apos;ll have full access to our free and premium products..
        /// </summary>
        internal static string To_activate_your_account__please_click_on_the_button_below_to_verify_your_email_address__Once_activated__you_ll_have_full_access_to_our_free_and_premium_products_ {
            get {
                return ResourceManager.GetString("To activate your account, please click on the button below to verify your email a" +
                        "ddress. Once activated, you ll have full access to our free and premium products" +
                        ".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To avoid any disruptions in accessing our service, we recommend that you generate a new API key before the mentioned date..
        /// </summary>
        internal static string To_avoid_any_disruptions_in_accessing_our_service__we_recommend_that_you_generate_a_new_API_key_before_the_mentioned_date_ {
            get {
                return ResourceManager.GetString("To avoid any disruptions in accessing our service, we recommend that you generate" +
                        " a new API key before the mentioned date.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We would like to inform you that your API key is about to expire on .
        /// </summary>
        internal static string We_would_like_to_inform_you_that_your_API_key_is_about_to_expire_on_ {
            get {
                return ResourceManager.GetString("We would like to inform you that your API key is about to expire on ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to Septeo!.
        /// </summary>
        internal static string Welcome_to_Septeo_ {
            get {
                return ResourceManager.GetString("Welcome to Septeo!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are receiving this email because we received a password reset request for your account. To proceed with the password reset please click on the button below:.
        /// </summary>
        internal static string You_are_receiving_this_email_because_we_received_a_password_reset_request_for_your_account__To_proceed_with_the_password_reset_please_click_on_the_button_below_ {
            get {
                return ResourceManager.GetString("You are receiving this email because we received a password reset request for you" +
                        "r account. To proceed with the password reset please click on the button below:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are receiving this email because your account is locked out, to proceed with the password reset please click on the button below:.
        /// </summary>
        internal static string You_are_receiving_this_email_because_your_account_is_locked_out__to_proceed_with_the_password_reset_please_click_on_the_button_below_ {
            get {
                return ResourceManager.GetString("You are receiving this email because your account is locked out, to proceed with " +
                        "the password reset please click on the button below:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Septeo password was just changed..
        /// </summary>
        internal static string Your_Septeo_password_was_just_changed_ {
            get {
                return ResourceManager.GetString("Your Septeo password was just changed.", resourceCulture);
            }
        }
    }
}
